config/routes.rb
ServiceEntrance::Application.routes.draw do
  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"


  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
    resources :exhibits
    resources :notes
    resources :medias
  end

end

app/models/exhibit.rb
class Exhibit < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  paginates_per 100

  SUBTYPES = %w(
    object
    painting
    sculpture
  )

  validates :subtype,
    inclusion: { in: SUBTYPES,
                 message: "%{value} is not a valid subtype" }

  validates :name,
            :author,
            :year,
            :materials,
            :size,
            :owner,
            :image,
            presence: true

  def self.search_and_order(search, page_number)
    if search
      where("name LIKE ?", "%#{search.downcase}%").page page_number
    else
      page(page_number)
    end
  end
end

app/controllers/admin/exhibits_controller.rb
class Admin::ExhibitsController < Admin::BaseController
  before_action :set_exhibit, only: [ :show, :edit, :update, :destroy ]

  def index
    @exhibits = Exhibit.search_and_order params[:search], params[:page]
  end

  def new
    @exhibit = Exhibit.new
  end

  def edit
  end

  def update
    if @exhibit.update(exhibit_params)
      redirect_to admin_exhibits_path, notice: 'Exhibit updated'
    else
      flash[:alert] = "Exhibit couldn't be updated."
      render :edit
    end
  end

  def create
    @exhibit = Exhibit.create exhibit_params
    if @exhibit
      redirect_to admin_exhibits_path, notice: 'Exhibit created'
    else
      flash[:alert] = "Exhibit couldn't be created"
      render :new
    end
  end

  def destroy
    if @exhibit.destroy
      redirect_to admin_exhibits_path, notice: 'Exhibit destroyed'
    else
      flash[:alert] = "Exhibit couldn't be destroyed"
      redirect_to admin_users_path
    end
  end

  private

  def set_exhibit
    @exhibit = Exhibit.find(params[:id])
  rescue
    flash[:alert] = "The exhibit with an id of #{params[:id]} doesn't exist."
    redirect_to admin_exhibits_path
  end

  def exhibit_params
    params.require(:exhibit).permit :subtype,
                                    :name,
                                    :author,
                                    :year,
                                    :materials,
                                    :size,
                                    :owner,
                                    :image
  end
end

app/helpers/admin/exhibits_helper.rb
module Admin::ExhibitsHelper
end

app/views/admin/exhibits/_form.html.slim
= form_for [:admin, @exhibit], :html => { role: 'form', multipart: true, class: 'form-horizontal' } do |f|
  .form-group 
    = f.label :subtype, class: 'col-sm-3 control-label'
    .col-sm-6
      - Exhibit::SUBTYPES.each do |subtype|
        label.radio-inline
          = f.radio_button :subtype, subtype
          = subtype
  .form-group
    = f.label :name, class: 'col-sm-3 control-label'
    .col-sm-6 = f.text_field :name, autofocus: true, class: 'form-control'
  .form-group
    = f.label :author, class: 'col-sm-3 control-label'
    .col-sm-6 = f.text_field :author, class: 'form-control'
  .form-group
    = f.label :year, class: 'col-sm-3 control-label'
    .col-sm-6 = f.text_field :year, class: 'form-control'
  .form-group
    = f.label :materials, class: 'col-sm-3 control-label'
    .col-sm-6 = f.text_field :materials, class: 'form-control'
  .form-group
    = f.label :size, class: 'col-sm-3 control-label'
    .col-sm-6 = f.text_field :size, class: 'form-control'
  .form-group
    = f.label :owner, class: 'col-sm-3 control-label'
    .col-sm-6 = f.text_field :owner, class: 'form-control'
  .form-group
    = f.label :image, class: 'col-sm-3 control-label'
    .col-sm-6
      - if @exhibit.image?
        p = image_tag(@exhibit.image.thumb)
      = f.file_field :image
    = f.hidden_field :image_cache
        
  .row: .col-sm-6.col-sm-offset-3
    = f.submit class: 'btn btn-danger'
    = link_to "Back to exhibits", admin_exhibits_path, class: 'btn btn-link'

app/views/admin/exhibits/edit.html.slim
h1 Edit exhibit

= render 'form'

app/views/admin/exhibits/index.html.slim
h1 Exhibits <small>Admin</small>
p = link_to("Back to Admin", admin_root_path)

div.text-center
  p = page_entries_info @exhibits
  = paginate @exhibits

.row
  .col-sm-6
    = form_tag admin_exhibits_path, method: 'get', role: "form", class: 'form-inline' do
      .form-group
        = text_field_tag :search, params[:search], class: 'form-control input-sm'
      |  
      = submit_tag "Search", name: nil, class: "btn btn-sm btn-primary"
      |  
      = link_to "All", admin_exhibits_path, class: "btn btn-sm btn-link"
  .col-sm-6.text-right
    p = link_to "New exhibit", new_admin_exhibit_path, class: 'btn btn-primary'

table.table.table-striped
  tr
    th Subtype
    th Name
    th Author
    th Year
    th Materials
    th Size
    th Owner
    th Image
    th 

  - @exhibits.each do |exhibit|
    tr
      td = exhibit.subtype
      td = exhibit.name
      td = exhibit.author
      td = exhibit.year
      td = exhibit.materials
      td = exhibit.size
      td = exhibit.owner
      td = image_tag(exhibit.image.thumb)
      td
        = link_to "Edit", edit_admin_exhibit_path(exhibit), class: 'btn btn-sm btn-link'
        |  
        = button_to "Delete", admin_exhibit_path(exhibit, action: :destroy), method: :delete, data: { confirm: 'Are you sure to delete exhibit?' }, class: "btn btn-sm btn-danger"

div.text-center
  p = page_entries_info @exhibits
  = paginate @exhibits

app/views/admin/exhibits/new.html.slim
h1 New exhibit

= render 'form'