config/routes.rb
ServiceEntrance::Application.routes.draw do
  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"


  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
    resources :exhibits
    resources :notes
    resources :medias
  end

end

app/models/media.rb
class Media < ActiveRecord::Base
  paginates_per 100

  validates :embed,
            presence: true

  def self.search_and_order(search, page_number)
    if search
      where("name LIKE ?", "%#{search.downcase}%").page page_number
    else
      page(page_number)
    end
  end
end

app/controllers/admin/medias_controller.rb
class Admin::MediasController < ApplicationController
  before_action :set_note, only: [ :show, :edit, :update, :destroy ]

  def index
    @medias = Media.search_and_order params[:search], params[:page]
  end

  def new
    @media = Media.new
  end

  def edit
  end

  def update
    if @media.update(media_params)
      redirect_to admin_medias_path, notice: 'Media updated'
    else
      flash[:alert] = "Media couldn't be updated."
      render :edit
    end
  end

  def create
    @media = Media.create exhibit_params
    if @media
      redirect_to admin_medias_path, notice: 'Media created'
    else
      flash[:alert] = "Media couldn't be created"
      render :new
    end
  end

  def destroy
    if @media.destroy
      redirect_to admin_medias_path, notice: 'Media destroyed'
    else
      flash[:alert] = "Media couldn't be destroyed"
      redirect_to admin_users_path
    end
  end

  private

  def set_note
    @media = Media.find(params[:id])
  rescue
    flash[:alert] = "The note with an id of #{params[:id]} doesn't exist."
    redirect_to admin_medias_path
  end

  def exhibit_params
    params.require(:media).permit :name, :embed
  end
end

app/helpers/admin/medias_helper.rb
module Admin::MediasHelper
end

app/views/admin/medias/_form.html.slim
= form_for [:admin, @media], :html => { role: 'form', multipart: true, class: 'form-horizontal' } do |f|
  .form-group
    = f.label :name, class: 'col-sm-3 control-label'
    .col-sm-6 = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :embed, class: 'col-sm-3 control-label'
    .col-sm-6 = f.text_area :embed, autofocus: true, class: 'form-control'

  .row: .col-sm-6.col-sm-offset-3
    = f.submit class: 'btn btn-danger'
    = link_to "Back to other media", admin_medias_path, class: 'btn btn-link'

app/views/admin/medias/edit.html.slim
h1 Edit media

= render 'media'

app/views/admin/medias/index.html.slim
h1 Media <small>Admin</small>
p = link_to("Back to Admin", admin_root_path)

div.text-center
  p = page_entries_info @medias
  = paginate @medias

.row
  .col-sm-6
    = form_tag admin_medias_path, method: 'get', role: "form", class: 'form-inline' do
      .form-group
        = text_field_tag :search, params[:search], class: 'form-control input-sm'
      |  
      = submit_tag "Search", name: nil, class: "btn btn-sm btn-primary"
      |  
      = link_to "All", admin_medias_path, class: "btn btn-sm btn-link"
  .col-sm-6.text-right
    p = link_to "New media", new_admin_media_path, class: 'btn btn-primary'

table.table.table-striped
  tr
    th Name
    th Content
    th 

  - @media.each do |media|
    tr
      td = media.name
      td = media.embed.sub('{{width}}', '640').sub('{{height}}', '360').html_safe
      td
        = link_to "Edit", edit_admin_media_path(media), class: 'btn btn-sm btn-link'
        |  
        = button_to "Delete", admin_media_path(media, action: :destroy), method: :delete, data: { confirm: 'Are you sure to delete media?' }, class: "btn btn-sm btn-danger"

div.text-center
  p = page_entries_info @medias
  = paginate @medias

app/views/admin/medias/new.html.slim
h1 New media

= render 'media'