config/routes.rb
ServiceEntrance::Application.routes.draw do
  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"


  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
    resources :exhibits
    resources :notes
    resources :medias
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :require_admin!

  def index
    @last_signups = User.last_signups(10)
    @last_signins = User.last_signins(10)
    @count = User.users_count
  end
end

app/views/admin/base/index.html.erb
<h1>Admin <small>Home</small></h1>
<div class="row">
  <div class="col-sm-4">
    <h3>Menu</h3>
    <h4><%= link_to "Users", admin_users_path %> <small>- <%= "#{@count} users" %></small></h4>
    <h4><%= link_to "Exhibits", admin_exhibits_path %></h4>
    <h4><%= link_to "Notes", admin_notes_path %></h4>
    <hr/>
  </div>

  <div class="col-sm-4">
    <h3>Last Sign Ups</h3>
    <ul class="list-unstyled">
      <% @last_signups.each do |user| %>
      <li class="list-padded-bottom">
        <%= link_to user.username, edit_admin_user_path(user) %><br/>
        <small><%= time_ago_in_words(user.created_at)%> ago</small>
      </li>
      <% end %>
    </ul>
  </div>

  <div class="col-sm-4">
    <h3>Last Sign Ins</h3>
    <ul class="list-unstyled">
      <% @last_signins.each do |user| %>
      <li class="list-padded-bottom">
        <%= link_to user.username, edit_admin_user_path(user) %><br/>
        <small>
          <% unless user.last_sign_in_at.nil? %>
          <%= time_ago_in_words(user.last_sign_in_at)%> ago
          <% else %>
          never
          <% end %>
        </small>
      </li>
      <% end %>
    </ul>
  </div>

</div>