config/routes.rb
ServiceEntrance::Application.routes.draw do
  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"


  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
    resources :exhibits
    resources :notes
    resources :medias
  end

end

app/models/note.rb
class Note < ActiveRecord::Base
  paginates_per 100

  validates :body,
            :author,
            presence: true

  def self.search_and_order(search, page_number)
    if search
      where("body LIKE ?", "%#{search.downcase}%").page page_number
    else
      page(page_number)
    end
  end
end

app/controllers/admin/notes_controller.rb
class Admin::NotesController < Admin::BaseController
  before_action :set_note, only: [ :show, :edit, :update, :destroy ]

  def index
    @notes = Note.search_and_order params[:search], params[:page]
  end

  def new
    @note = Note.new
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to admin_notes_path, notice: 'Note updated'
    else
      flash[:alert] = "Note couldn't be updated."
      render :edit
    end
  end

  def create
    @note = Note.create exhibit_params
    if @note
      redirect_to admin_notes_path, notice: 'Note created'
    else
      flash[:alert] = "Note couldn't be created"
      render :new
    end
  end

  def destroy
    if @note.destroy
      redirect_to admin_notes_path, notice: 'Note destroyed'
    else
      flash[:alert] = "Note couldn't be destroyed"
      redirect_to admin_users_path
    end
  end

  private

  def set_note
    @note = Note.find(params[:id])
  rescue
    flash[:alert] = "The note with an id of #{params[:id]} doesn't exist."
    redirect_to admin_notes_path
  end

  def exhibit_params
    params.require(:note).permit :body, :author
  end
end

app/helpers/admin/notes_helper.rb
module Admin::NotesHelper
end

app/views/admin/notes/_form.html.slim
= form_for [:admin, @note], :html => { role: 'form', multipart: true, class: 'form-horizontal' } do |f|
  .form-group
    = f.label :body, class: 'col-sm-3 control-label'
    .col-sm-6 = f.text_area :body, autofocus: true, class: 'form-control'
  .form-group
    = f.label :author, class: 'col-sm-3 control-label'
    .col-sm-6 = f.text_field :author, class: 'form-control'

  .row: .col-sm-6.col-sm-offset-3
    = f.submit class: 'btn btn-danger'
    = link_to "Back to notes", admin_notes_path, class: 'btn btn-link'

app/views/admin/notes/edit.html.slim
h1 Edit note

= render 'form'

app/views/admin/notes/index.html.slim
h1 Notes <small>Admin</small>
p = link_to("Back to Admin", admin_root_path)

div.text-center
  p = page_entries_info @notes
  = paginate @notes

.row
  .col-sm-6
    = form_tag admin_notes_path, method: 'get', role: "form", class: 'form-inline' do
      .form-group
        = text_field_tag :search, params[:search], class: 'form-control input-sm'
      |  
      = submit_tag "Search", name: nil, class: "btn btn-sm btn-primary"
      |  
      = link_to "All", admin_notes_path, class: "btn btn-sm btn-link"
  .col-sm-6.text-right
    p = link_to "New note", new_admin_note_path, class: 'btn btn-primary'

table.table.table-striped
  tr
    th Text
    th Author
    th 

  - @notes.each do |note|
    tr
      td = note.body
      td = note.author
      td
        = link_to "Edit", edit_admin_note_path(note), class: 'btn btn-sm btn-link'
        |  
        = button_to "Delete", admin_note_path(note, action: :destroy), method: :delete, data: { confirm: 'Are you sure to delete note?' }, class: "btn btn-sm btn-danger"

div.text-center
  p = page_entries_info @notes
  = paginate @notes

app/views/admin/notes/new.html.slim
h1 New note

= render 'form'